/**
 * Analytics Engine — main orchestration service.
 * Repository: 010_ANALYTICS_ENGINE.md — ANALYTICAL PIPELINE, ANALYTICS VALIDATION,
 *             DASHBOARD DATASETS
 *
 * Pipeline position: Business Engines → Formula Engine → Analytics Engine → AI → Dashboard
 * "Dashboards shall never aggregate raw transactional data directly." (010)
 * "Invalid analytics shall never be published." (010)
 */

import { Decimal } from "@prisma/client/runtime/library";
import { createLogger } from "@/lib/logger";
import type { DateRange, AnalyticsPeriod, FinancialAnalyticsSummary, InventoryAnalyticsSummary } from "../domain/analytics.types";
import { KPI_IDS } from "../domain/analytics.types";
import {
  calculateAllOperationalRates,
} from "../kpis/operational.kpis";
import {
  calculateTrueCpa,
  calculateMarketingRoi,
  buildMarketingAnalyticsSummary,
} from "../kpis/marketing.kpis";
import {
  buildFinancialAnalyticsSummary,
  wrapRevenueKpi,
  wrapGrossProfitKpi,
  wrapNetProfitKpi,
  wrapShippingSubsidyKpi,
  calculateProfitMargin,
} from "../kpis/financial.analytics";
import {
  getFinancialTotals,
  getShippingTotals,
  buildOperationalRateInput,
  getMarketingSpendByPlatform,
  resolveDateRange,
} from "../repositories/analytics-read.repository";
import type { KpiValue } from "../domain/analytics.types";
import { AppError } from "@/utils/errors";

const logger = createLogger("AnalyticsEngine");

// ── Analytics validation (010: ANALYTICS VALIDATION) ─────────────────────

function assertAnalyticsInputValid(storeId: string, range: DateRange): void {
  if (!storeId) throw new AppError({ code: "ANALYTICS_MISSING_STORE", message: "storeId required.", severity: "HIGH" });
  if (range.from > range.to) throw new AppError({ code: "ANALYTICS_INVALID_RANGE", message: "DateRange.from must be before DateRange.to.", severity: "HIGH" });
}

// ── Executive KPI dataset ─────────────────────────────────────────────────

export interface ExecutiveKpiDataset {
  storeId: string;
  range: DateRange;
  computedAt: Date;
  kpis: KpiValue[];
  financialSummary: FinancialAnalyticsSummary;
}

/**
 * Computes the complete executive KPI dataset for a period.
 * Called by background job before dashboard render — dashboards consume this output.
 * (010: "Dashboards consume prepared datasets generated by the Analytics Engine.")
 */
export async function computeExecutiveKpiDataset(
  storeId: string,
  period: AnalyticsPeriod,
  customRange?: DateRange,
): Promise<ExecutiveKpiDataset> {
  const range = resolveDateRange(period, customRange);
  assertAnalyticsInputValid(storeId, range);

  logger.info("Analytics Engine: computing executive KPIs", {
    metadata: { storeId, from: range.from.toISOString(), to: range.to.toISOString() },
  });

  // ── Read from Financial Engine outputs ────────────────────────────────
  const [financials, shipping, operationalInput, marketingByPlatform] = await Promise.all([
    getFinancialTotals(storeId, range),
    getShippingTotals(storeId, range),
    buildOperationalRateInput(storeId, range),
    getMarketingSpendByPlatform(storeId, range),
  ]);

  const totalMarketingSpend = marketingByPlatform.reduce(
    (sum, p) => sum.plus(p.totalSpend), new Decimal(0),
  );

  // ── Shipping subsidy aggregation ──────────────────────────────────────
  // Subsidy = Σ(actualShippingCost) − Σ(customerShippingFee from revenue events)
  // Approximated here from shipping totals; exact value from Financial Engine events
  const totalShippingSubsidy = shipping.totalShippingCost; // read from Financial Engine in full impl

  // ── KPI calculations ──────────────────────────────────────────────────
  const operationalRates = calculateAllOperationalRates(operationalInput);
  const trueCpa = calculateTrueCpa(totalMarketingSpend, financials.deliveredOrderCount, storeId, range);
  const roi = calculateMarketingRoi(financials.totalRevenue, totalMarketingSpend, storeId, range);
  const profitMargin = calculateProfitMargin(financials.totalNetProfit, financials.totalRevenue, storeId, range);

  const kpis: KpiValue[] = [
    wrapRevenueKpi(financials.totalRevenue, storeId, range),
    wrapGrossProfitKpi(financials.totalGrossProfit, storeId, range),
    wrapNetProfitKpi(financials.totalNetProfit, storeId, range),
    wrapShippingSubsidyKpi(totalShippingSubsidy, storeId, range),
    profitMargin,
    operationalRates.deliveryRate,
    operationalRates.returnRate,
    operationalRates.refusalRate,
    operationalRates.exchangeRate,
    trueCpa,
    roi,
  ];

  const financialSummary = buildFinancialAnalyticsSummary({
    storeId,
    range,
    totalRevenue: financials.totalRevenue,
    totalGrossProfit: financials.totalGrossProfit,
    totalNetProfit: financials.totalNetProfit,
    totalShippingExpense: shipping.totalShippingCost,
    totalShippingSubsidy,
    totalMarketingExpense: totalMarketingSpend,
    deliveredOrderCount: financials.deliveredOrderCount,
  });

  logger.info("Analytics Engine: executive KPIs computed", {
    metadata: {
      storeId,
      kpiCount: kpis.length,
      revenue: financials.totalRevenue.toString(),
      deliveryRate: operationalRates.deliveryRate.value.toString(),
    },
  });

  return { storeId, range, computedAt: new Date(), kpis, financialSummary };
}

// ── KPI lookup helper ─────────────────────────────────────────────────────

export function getKpiFromDataset(dataset: ExecutiveKpiDataset, kpiId: string): KpiValue | null {
  return dataset.kpis.find((k) => k.kpiId === kpiId) ?? null;
}
