/**
 * AI explanation layer.
 * Repository: 011_AI_ENGINE.md v2.0.0
 *
 * "AI explains, summarizes, answers questions, and assists." (011)
 * "Every AI explanation must reference Formula IDs, KPI IDs, Score IDs, Decision IDs." (011)
 * "AI must NOT generate Product Scores, Campaign Scores, Opportunity Scores,
 *  Risk Scores, or recommendations independently." (011)
 *
 * Scaffold: no real LLM integration. Explanation templates consume engine outputs
 * and produce structured, reference-annotated text ready for LLM enhancement
 * in a future sprint.
 */

import type { AiContext, AiExplanation, AiReference, AiDailyBrief, AiDailyBriefSection } from "../types/ai.types";
import { createLogger } from "@/lib/logger";

const logger = createLogger("AiExplanationLayer");
const MODEL_VERSION = "scaffold-1.0.0";

// ── Build references from context ─────────────────────────────────────────

function buildReferences(context: AiContext, additionalRefs: AiReference[] = []): AiReference[] {
  const refs: AiReference[] = [...additionalRefs];

  (context.scores ?? []).forEach(s => {
    refs.push({ type: "SCORE", id: s.scoreId, label: s.scoreName, value: String(s.score) });
  });
  (context.decisions ?? []).slice(0, 3).forEach(d => {
    refs.push({ type: "DECISION", id: d.decisionId, label: d.decisionName, value: d.priority });
  });
  Object.entries(context.kpis ?? {}).forEach(([id, v]) => {
    refs.push({ type: "KPI", id: v.kpiId, label: id, value: v.value });
    refs.push({ type: "FORMULA", id: v.formulaId, label: `Formula ${v.formulaId}` });
  });

  // Deduplicate by id
  return refs.filter((r, i, arr) => arr.findIndex(x => x.id === r.id) === i);
}

// ── Explanation: why did a score change ───────────────────────────────────

export function explainScore(scoreId: string, context: AiContext): AiExplanation {
  const score = (context.scores ?? []).find(s => s.scoreId === scoreId);
  if (!score) {
    return {
      role: "EXPLAIN",
      text: `Score ${scoreId} not found in current context. Run Score Engine to generate scores.`,
      references: [{ type: "SCORE", id: scoreId, label: scoreId }],
      confidence: "INSUFFICIENT_DATA",
      confidencePct: 0,
      generatedAt: new Date().toISOString(),
      modelVersion: MODEL_VERSION,
    };
  }

  const trendWord = score.delta >= 0 ? "improved" : "declined";
  const topComponents = score.components
    .sort((a, b) => b.contribution - a.contribution)
    .slice(0, 3)
    .map(c => `${c.name} (contributed ${c.contribution.toFixed(1)} pts)`)
    .join(", ");

  const text = `${score.scoreName} (${score.scoreId}) is at ${score.score}/100 (${score.grade}). ` +
    `The score has ${trendWord} by ${Math.abs(score.delta)} points compared to the previous period. ` +
    `The top contributing components are: ${topComponents}. ` +
    `${score.recommendedActions[0] ?? "Monitor closely."}`;

  logger.debug("Score explanation generated", { metadata: { scoreId, score: score.score } });

  return {
    role: "EXPLAIN",
    text,
    references: buildReferences(context, [
      { type: "SCORE", id: scoreId, label: score.scoreName, value: String(score.score) },
    ]),
    confidence: "HIGH",
    confidencePct: 85,
    generatedAt: new Date().toISOString(),
    modelVersion: MODEL_VERSION,
  };
}

// ── Explanation: why was a decision triggered ──────────────────────────────

export function explainDecision(decisionId: string, context: AiContext): AiExplanation {
  const decision = (context.decisions ?? []).find(d => d.decisionId === decisionId);
  if (!decision) {
    return {
      role: "EXPLAIN",
      text: `Decision ${decisionId} not found in current context.`,
      references: [{ type: "DECISION", id: decisionId, label: decisionId }],
      confidence: "INSUFFICIENT_DATA",
      confidencePct: 0,
      generatedAt: new Date().toISOString(),
      modelVersion: MODEL_VERSION,
    };
  }

  const supportingScoreText = decision.supportingScores
    .map(sid => {
      const s = (context.scores ?? []).find(x => x.scoreId === sid);
      return s ? `${s.scoreName} (${sid}): ${s.score}` : sid;
    })
    .join(", ");

  const text = `Decision "${decision.decisionName}" (${decision.decisionId}) was triggered by ` +
    `${decision.triggeredByRule} with ${decision.priority} priority. ` +
    `Reason: ${decision.reason} ` +
    `Supporting scores: ${supportingScoreText || "None in context"}. ` +
    `Recommended action: ${decision.recommendedAction} ` +
    `Expected impact: ${decision.expectedImpact.impactLabel} — ${decision.expectedImpact.impactValue}. ` +
    `Confidence: ${Math.round(decision.confidence * 100)}%. ` +
    `Note: This recommendation was generated by the Decision Engine. AI narrates and explains; it does not generate recommendations independently.`;

  return {
    role: "EXPLAIN",
    text,
    references: buildReferences(context, [
      { type: "DECISION", id: decisionId, label: decision.decisionName, value: decision.priority },
      { type: "RULE", id: decision.triggeredByRule, label: decision.triggeredByRule },
      ...decision.supportingScores.map(id => ({ type: "SCORE" as const, id, label: id })),
      ...decision.supportingKpis.map(id => ({ type: "KPI" as const, id, label: id })),
      ...decision.supportingFormulaIds.map(id => ({ type: "FORMULA" as const, id, label: id })),
    ]),
    confidence: decision.confidence >= 0.8 ? "HIGH" : decision.confidence >= 0.6 ? "MEDIUM" : "LOW",
    confidencePct: Math.round(decision.confidence * 100),
    warnings: decision.confidence < 0.7 ? ["Confidence below 70% — collect more data before acting."] : undefined,
    generatedAt: new Date().toISOString(),
    modelVersion: MODEL_VERSION,
  };
}

// ── Answer a natural language question ────────────────────────────────────

export function answerQuery(question: string, context: AiContext): AiExplanation {
  const q = question.toLowerCase();
  let text: string;
  let refs: AiReference[] = [];

  if (q.includes("profit") || q.includes("margin")) {
    const kpi = context.kpis?.["Net Profit"];
    text = kpi
      ? `Net Profit is ${kpi.value} (KPI-FIN-003, formula FIN-002). This is calculated as Revenue − COGS − Shipping − Marketing − Variable − Fixed Expenses ± Adjustments. The value comes from the Financial Engine — AI never recalculates it.`
      : "Net Profit data is not in the current context. Please check the Financial Dashboard or run the Analytics Engine.";
    refs = [{ type: "KPI", id: "KPI-FIN-003", label: "Net Profit" }, { type: "FORMULA", id: "FIN-002", label: "Net Profit Formula" }];
  } else if (q.includes("campaign") || q.includes("cpa") || q.includes("roas")) {
    const campScore = (context.scores ?? []).find(s => s.scoreId === "SCORE-003");
    text = campScore
      ? `Campaign performance is represented by Campaign Score (SCORE-003): ${campScore.score}/100 (${campScore.grade}). ` +
        `True CPA (KPI-MKT-002, MKT-002) is the key marketing efficiency metric. ` +
        `${campScore.score < 60 ? "Campaign Score below 60 — Decision Engine recommends reviewing campaigns (DEC-RULE-003)." : "Campaign performance is acceptable."}`
      : "Campaign Score (SCORE-003) not available. Run Score Engine first.";
    refs = [{ type: "SCORE", id: "SCORE-003", label: "Campaign Score" }, { type: "KPI", id: "KPI-MKT-002", label: "True CPA" }];
  } else if (q.includes("inventory") || q.includes("stock")) {
    const invScore = (context.scores ?? []).find(s => s.scoreId === "SCORE-006");
    text = invScore
      ? `Inventory Health (SCORE-006) is ${invScore.score}/100 (${invScore.grade}). ` +
        `${invScore.score < 60 ? "Inventory Health is declining — check low stock alerts and consider purchasing (DEC-004 from Decision Engine)." : "Inventory appears healthy."}`
      : "Inventory Health Score (SCORE-006) not available.";
    refs = [{ type: "SCORE", id: "SCORE-006", label: "Inventory Health" }];
  } else {
    text = `I can help explain business performance using Score Engine outputs (SCORE-001 through SCORE-009), ` +
      `Decision Engine recommendations (DEC-001 through DEC-010), and Financial Engine data (FIN-001 through FIN-004). ` +
      `I do not generate scores or recommendations independently — those come exclusively from the respective engines.`;
    refs = [
      { type: "SCORE", id: "SCORE-001", label: "Business Health" },
      { type: "DECISION", id: "DEC-001", label: "Scale Campaign" },
    ];
  }

  return {
    role: "ANSWER",
    text,
    references: [...refs, ...buildReferences(context)].filter((r, i, arr) => arr.findIndex(x => x.id === r.id) === i),
    confidence: "HIGH",
    confidencePct: 80,
    generatedAt: new Date().toISOString(),
    modelVersion: MODEL_VERSION,
  };
}

// ── Daily Brief generator ─────────────────────────────────────────────────

export function generateDailyBrief(context: AiContext): AiDailyBrief {
  const scores = context.scores ?? [];
  const decisions = context.decisions ?? [];
  const bizHealth = scores.find(s => s.scoreId === "SCORE-001");
  const riskScore  = scores.find(s => s.scoreId === "SCORE-009");

  const sections: AiDailyBriefSection[] = [
    {
      sectionKey: "business_health",
      title: "Business Health",
      titleAr: "صحة الأعمال",
      content: bizHealth
        ? `Business Health (SCORE-001) is ${bizHealth.score}/100 — ${bizHealth.grade}. ` +
          `Trend: ${bizHealth.trend}. Delta: ${bizHealth.delta >= 0 ? "+" : ""}${bizHealth.delta} pts. ` +
          `${bizHealth.recommendedActions[0] ?? ""}`
        : "Business Health Score not yet available. Run Score Engine to generate.",
      kpiRefs: ["KPI-FIN-001", "KPI-FIN-003"],
      decisionRefs: decisions.filter(d => d.priority === "CRITICAL").map(d => d.decisionId),
    },
    {
      sectionKey: "risk_alerts",
      title: "Risk Alerts",
      titleAr: "تنبيهات المخاطر",
      content: riskScore && riskScore.score >= 70
        ? `Risk Score (SCORE-009) is elevated at ${riskScore.score}/100. ` +
          `${decisions.filter(d => d.priority === "CRITICAL").length} CRITICAL decision(s) require attention. ` +
          `Review the Decision Center immediately.`
        : "Risk level is within acceptable range. Monitor standard KPIs.",
      kpiRefs: [],
      decisionRefs: decisions.filter(d => d.priority === "CRITICAL").map(d => d.decisionId),
    },
    {
      sectionKey: "recommended_actions",
      title: "Recommended Actions",
      titleAr: "الإجراءات الموصى بها",
      content: decisions.filter(d => ["CRITICAL", "HIGH"].includes(d.priority)).length > 0
        ? `${decisions.filter(d => ["CRITICAL","HIGH"].includes(d.priority)).length} high-priority action(s) from Decision Engine:\n` +
          decisions.filter(d => ["CRITICAL","HIGH"].includes(d.priority))
            .map(d => `• [${d.priority}] ${d.decisionName} (${d.decisionId}): ${d.recommendedAction}`)
            .join("\n")
        : "No high-priority actions from Decision Engine at this time.",
      kpiRefs: [],
      decisionRefs: decisions.filter(d => ["CRITICAL","HIGH"].includes(d.priority)).map(d => d.decisionId),
    },
  ];

  const scoresSummary = scores.length > 0
    ? scores.map(s => `${s.scoreName} (${s.scoreId}): ${s.score} — ${s.grade}`).join(" | ")
    : "Scores not yet generated. Run Score Engine.";

  const decisionsSummary = decisions.length > 0
    ? `${decisions.length} active decisions from Decision Engine. ` +
      `${decisions.filter(d => d.priority === "CRITICAL").length} CRITICAL, ` +
      `${decisions.filter(d => d.priority === "HIGH").length} HIGH priority.`
    : "No active decisions from Decision Engine.";

  return {
    briefId: crypto.randomUUID(),
    storeId: context.storeId,
    generatedAt: new Date().toISOString(),
    period: "TODAY",
    locale: context.locale,
    sections,
    scoresSummary,
    decisionsSummary,
    priorityActions: decisions
      .filter(d => ["CRITICAL","HIGH"].includes(d.priority))
      .map(d => `${d.decisionName}: ${d.recommendedAction}`),
    confidence: 0.82,
    references: buildReferences(context),
  };
}
