"use client";
/**
 * Decision Center — Pre-Preview.
 * Repository: 055_DECISION_ENGINE.md — DECISION CENTER, BR-DEC-002
 * Shows Decision Engine outputs. AI narrates only — never generates decisions.
 * BR-DEC-002: User approval required. No auto-execution.
 */
import { useState } from "react";
import { MOCK_DECISIONS, MOCK_SMART_ALERTS, MOCK_SCORES } from "@/lib/dashboard/mock-data";
import { DecisionCard } from "@/components/decisions/DecisionCard";
import { SmartAlert } from "@/components/shared/index";
import { ScoreCard } from "@/components/scores/ScoreCard";
import { MOCK_SCORE_HISTORY } from "@/lib/dashboard/mock-data";
import { cn } from "@/lib/utils";

const TABS = ["All", "CRITICAL", "HIGH", "MEDIUM", "LOW"] as const;

export default function DecisionCenterPage() {
  const [activeTab, setActiveTab] = useState<typeof TABS[number]>("All");
  const [dismissed, setDismissed] = useState<string[]>([]);

  const filtered = activeTab === "All"
    ? MOCK_DECISIONS
    : MOCK_DECISIONS.filter(d => d.priority === activeTab);

  const riskScore  = MOCK_SCORES.find(s => s.scoreId === "SCORE-009");
  const oppScore   = MOCK_SCORES.find(s => s.scoreId === "SCORE-008");

  return (
    <div className="min-h-screen bg-gray-50 p-4 md:p-6 space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-xl font-bold text-gray-900">Decision Center</h1>
        <p className="text-sm text-gray-500 mt-0.5">
          Decision Engine outputs (055_DECISION_ENGINE). AI explains — never generates.
          BR-DEC-002: All decisions require user approval.
        </p>
      </div>

      {/* Smart alerts */}
      <div className="space-y-2">
        <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Smart Alerts (from Decision Engine)</p>
        {MOCK_SMART_ALERTS.filter(a => !dismissed.includes(a.alertId)).map(alert => (
          <SmartAlert key={alert.alertId} {...(alert as any)}
            onDismiss={() => setDismissed(d => [...d, alert.alertId])}
            onViewDecision={() => {}}
          />
        ))}
        {MOCK_SMART_ALERTS.every(a => dismissed.includes(a.alertId)) && (
          <p className="text-sm text-gray-400 italic py-2">All alerts dismissed.</p>
        )}
      </div>

      {/* Risk vs Opportunity scores */}
      {riskScore && oppScore && (
        <div className="grid md:grid-cols-2 gap-3">
          <ScoreCard {...(riskScore as any)}
            history={MOCK_SCORE_HISTORY["SCORE-009"]}
            onInspect={() => {}}
          />
          <ScoreCard {...(oppScore as any)}
            history={MOCK_SCORE_HISTORY["SCORE-008"]}
            onInspect={() => {}}
          />
        </div>
      )}

      {/* Priority filter tabs */}
      <div className="flex gap-1 overflow-x-auto">
        {TABS.map(tab => (
          <button key={tab} onClick={() => setActiveTab(tab)}
            className={cn(
              "shrink-0 rounded-lg px-3 py-1.5 text-xs font-medium border transition-colors",
              activeTab === tab
                ? "bg-indigo-600 text-white border-indigo-600"
                : "bg-white text-gray-600 border-gray-200 hover:bg-gray-50",
            )}>
            {tab}
            {tab !== "All" && (
              <span className="ml-1 opacity-70">({MOCK_DECISIONS.filter(d => d.priority === tab).length})</span>
            )}
          </button>
        ))}
      </div>

      {/* Decision cards */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">
        {filtered.map(dec => (
          <DecisionCard key={dec.decisionId} {...(dec as any)}
            onAccept={() => alert(`[Preview] Accept: ${dec.decisionId}\nBR-DEC-002: Real acceptance would call /api/v1/decisions and require user confirmation.`)}
            onReject={() => alert(`[Preview] Reject: ${dec.decisionId}`)}
            onInspect={() => {}}
          />
        ))}
      </div>

      {filtered.length === 0 && (
        <div className="rounded-xl border-2 border-dashed border-gray-200 p-8 text-center">
          <p className="text-gray-400">No {activeTab === "All" ? "" : activeTab} decisions.</p>
        </div>
      )}

      {/* Architecture note */}
      <div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-xs text-indigo-700">
        <p className="font-semibold mb-1">Decision Engine Architecture (055_DECISION_ENGINE)</p>
        <p>Decisions are generated by 15 documented rules (DEC-RULE-001 through DEC-RULE-015).</p>
        <p className="mt-1">AI explains decisions — it never creates them. BR-DEC-001: Decision Engine never modifies business data.</p>
        <p className="mt-1">All decisions start as OPEN → ACKNOWLEDGED → ACCEPTED/REJECTED → ARCHIVED.</p>
      </div>
    </div>
  );
}
